### ISSUE TITLE
RuntimeError: CUDA error: out of memory (NVidia V100, 32 GB DDRAM)

### ISSUE THREAD

**Issue by burgetrm** [neuml/paperai#22]
What are the minimum memory requirements for the PaperAI?  When running on Nvidia V100, 32 GB DDRAM I got: RuntimeError: CUDA error: out of memory. GPU memory seems to be completely free.

Is there a way how to run it from GPU, or can I run it exclusively on TPUs?

```
from txtai.embeddings import Embeddings
import torch

torch.cuda.empty_cache()

# MEMORY
id = 1
t = torch.cuda.get_device_properties(id).total_memory
c = torch.cuda.memory_cached(id)
a = torch.cuda.memory_allocated(id)
f = c-a  # free inside cache

print("TOTAL", t / 1024/1024/1024," GB")
print("ALLOCATED", a)

# Create embeddings model, backed by sentence-transformers & transformers
embeddings = Embeddings({"method": "transformers", "path": "sentence-transformers/bert-base-nli-mean-tokens"})

import numpy as np

sections = ["US tops 5 million confirmed virus cases",
            "Canada's last fully intact ice shelf has suddenly collapsed, forming a Manhattan-sized iceberg",
            "Beijing mobilises invasion craft along coast as Taiwan tensions escalate",
            "The National Park Service warns against sacrificing slower friends in a bear attack",
            "Maine man wins $1M from $25 lottery ticket",
            "Make huge profits without work, earn up to $100,000 a day"]


query = "health"
uid = np.argmax(embeddings.similarity(query, sections))
print("%-20s %s" % (query, sections[uid]))
```

> TOTAL 31.74853515625  GB
> ALLOCATED 0
> Traceback (most recent call last):
>   File "pokus2.py", line 32, in <module>
>     uid = np.argmax(embeddings.similarity(query, sections))
>   File "/home/user/.local/lib/python3.8/site-packages/txtai/embeddings.py", line 228, in similarity
>     query = self.transform((None, query, None)).reshape(1, -1)
>   File "/home/user/.local/lib/python3.8/site-packages/txtai/embeddings.py", line 179, in transform
>     embedding = self.model.transform(document)
>   File "/home/user/.local/lib/python3.8/site-packages/txtai/vectors.py", line 264, in transform
>     return self.model.encode([" ".join(document[1])], show_progress_bar=False)[0]
>

**Comment by davidmezzetti** [comment]
Thank you for trying this out.

Looking at the issue, you're referencing the txtai demo. Are you trying txtai or paperai?

Did you install from the master branch or pip?

Do you have a device id = 0? I think what may be happening is that you have two video cards and it's using device id=0 not your V100 device. 

What happens when you run:

```python
from transformers import AutoModel
AutoModel.from_pretrained("sentence-transformers/bert-base-nli-mean-tokens")
```

**Comment by davidmezzetti** [comment]
Closing due to inactivity, feel free to re-open or file a new issue if there continues to be issues.
