### ISSUE TITLE
Report generation fails when index contains sections with no text

### ISSUE THREAD

**Issue by elshimone** [neuml/paperai#73]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/__main__.py", line 12, in <module>
    Execute.run(
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/execute.py", line 82, in run
    report.build(queries, options, output)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/common.py", line 99, in build
    self.articles(output, topn, (name, query, columns), results)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/common.py", line 160, in articles
    calculated = self.calculate(uid, metadata)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/common.py", line 198, in calculate
    sections = self.sections(uid)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/paperai/report/common.py", line 356, in sections
    if Tokenizer.tokenize(text):
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/txtai/pipeline/data/tokenizer.py", line 48, in tokenize
    return Tokenizer(lowercase, emoji, alphanum, stopwords)(text)
  File "/home/simon/pharmareview/venv/lib/python3.10/site-packages/txtai/pipeline/data/tokenizer.py", line 93, in __call__
    text = text.lower() if self.lowercase else text
```

Arguably the parser should not return sections with no text, but I don't think it would harm to guard against this.

**Comment by davidmezzetti** [comment]
This was fixed upstream in txtai 6.3.0

https://github.com/neuml/txtai/issues/607
